### ISSUE TITLE
Update Readme with example passing local AWS_PROFILE env var

### ISSUE THREAD

**Issue by quickliketurtle** [richarvey/aws-docker-toolkit#2]
Just started using this today. Dig the idea, and using a bash (or zsh in my case) alias doesn't require a change to workflow. Except for using multiple profiles. 

**Is your feature request related to a problem? Please describe.**
When working with multiple accounts, you need to pass the `--profile` flag with each command.

**Describe the solution you'd like**
With docker you can add `-e AWS_PROFILE` to set the AWS_PROFILE env var to the value of your local terminal session. 

**Describe alternatives you've considered**
n/a

**Additional context**
This works as is, this is just a suggestions to add to the readme. 

Happy to submit a PR for this if you think it's worth adding. 

Thanks.

**Comment by richarvey** [comment]
Please push a PR for this and I'll get it merged.
